const CAPABILITIES = Object.freeze([
  {
    id: 'research.discuss',
    aliases: ['research', 'investigate', 'analyse', 'analyze', 'audit', 'incele', 'arastir', 'analiz'],
    keywords: ['why', 'compare', 'audit', 'review', 'investigate', 'analyse', 'analyze', 'incele', 'arastir', 'analiz'],
    domain: 'research',
    risk: 'low',
    sideEffects: ['run_shell'],
    repoSignals: ['workflow_active'],
    preconditions: ['workflow_docs_ready'],
    postconditions: ['question_log_updated'],
    evidenceOutputs: ['docs/workflow/QUESTIONS.md', '.workflow/runtime/do-latest.json'],
    supportsMonorepo: true,
    supportsFrontend: true,
    supportsReview: true,
    codexModes: ['research', 'implement'],
  },
  {
    id: 'plan.execution_packet',
    aliases: ['plan', 'packet', 'roadmap', 'approach'],
    keywords: ['plan', 'packet', 'roadmap', 'approach', 'next step', 'milestone'],
    domain: 'plan',
    risk: 'low',
    sideEffects: ['write_fs'],
    repoSignals: ['workflow_active'],
    preconditions: ['workflow_docs_ready'],
    postconditions: ['packet_compiled'],
    evidenceOutputs: ['.workflow/packets', 'docs/workflow/EXECPLAN.md'],
    supportsMonorepo: true,
    supportsFrontend: true,
    supportsReview: true,
    codexModes: ['research', 'implement'],
  },
  {
    id: 'execute.quick_patch',
    aliases: ['implement', 'fix', 'patch', 'build', 'tamamla'],
    keywords: ['fix', 'implement', 'patch', 'build', 'land', 'complete', 'tamamla', 'duzelt'],
    domain: 'execute',
    risk: 'medium',
    sideEffects: ['write_fs', 'run_shell'],
    repoSignals: ['workflow_active'],
    preconditions: ['goal_present'],
    postconditions: ['verification_requested'],
    evidenceOutputs: ['.workflow/verifications/shell', '.workflow/reports/review.md'],
    supportsMonorepo: true,
    supportsFrontend: true,
    supportsReview: true,
    codexModes: ['implement', 'refactor'],
  },
  {
    id: 'review.deep_review',
    aliases: ['review', 'audit', 'code review', 'pr review', 'inceleme', 'degerlendirme', 'urun degerlendirmesi'],
    keywords: ['review', 'audit', 'regression', 'bug', 'risk', 'pr', 'diff', 'inceleme', 'degerlendirme', 'degerlendirmesi'],
    domain: 'review',
    risk: 'medium',
    sideEffects: ['run_shell', 'write_fs'],
    repoSignals: ['git_repo'],
    preconditions: ['git_or_patch_available'],
    postconditions: ['review_packet_written'],
    evidenceOutputs: ['.workflow/reports/review.md', '.workflow/reports/review-findings.json'],
    supportsMonorepo: true,
    supportsFrontend: true,
    supportsReview: true,
    codexModes: ['review'],
  },
  {
    id: 'review.re_review',
    aliases: ['re-review', 'rerun review', 'follow-up review'],
    keywords: ['re-review', 'rerun review', 'follow-up review', 'resolved issues'],
    domain: 'review',
    risk: 'medium',
    sideEffects: ['run_shell', 'write_fs'],
    repoSignals: ['git_repo'],
    preconditions: ['prior_review_exists'],
    postconditions: ['review_replay_written'],
    evidenceOutputs: ['.workflow/reports/review-replay.json', '.workflow/reports/review.md'],
    supportsMonorepo: true,
    supportsFrontend: true,
    supportsReview: true,
    codexModes: ['review'],
  },
  {
    id: 'frontend.ui_spec',
    aliases: ['ui spec', 'design contract', 'ui plan'],
    keywords: ['ui', 'frontend', 'screen', 'design', 'responsive', 'component', 'ux'],
    domain: 'frontend',
    risk: 'medium',
    sideEffects: ['write_fs'],
    repoSignals: ['frontend_active'],
    preconditions: ['frontend_surface_present'],
    postconditions: ['ui_spec_written'],
    evidenceOutputs: ['docs/workflow/UI-SPEC.md', 'docs/workflow/UI-PLAN.md'],
    supportsMonorepo: true,
    supportsFrontend: true,
    supportsReview: false,
    codexModes: ['frontend'],
  },
  {
    id: 'frontend.ui_review',
    aliases: ['ui review', 'visual audit', 'responsive audit', 'a11y audit'],
    keywords: ['ui review', 'visual', 'responsive', 'a11y', 'accessibility', 'screenshot', 'preview'],
    domain: 'frontend',
    risk: 'medium',
    sideEffects: ['run_shell', 'browser', 'write_fs'],
    repoSignals: ['frontend_active', 'browser_needed'],
    preconditions: ['frontend_surface_present'],
    postconditions: ['ui_review_written'],
    evidenceOutputs: ['docs/workflow/UI-REVIEW.md', '.workflow/verifications/browser'],
    supportsMonorepo: true,
    supportsFrontend: true,
    supportsReview: true,
    codexModes: ['frontend', 'review'],
  },
  {
    id: 'verify.shell',
    aliases: ['verify shell', 'test', 'check'],
    keywords: ['test', 'verify', 'check', 'lint', 'typecheck'],
    domain: 'verify',
    risk: 'low',
    sideEffects: ['run_shell'],
    repoSignals: ['workflow_active'],
    preconditions: ['command_available'],
    postconditions: ['shell_evidence_written'],
    evidenceOutputs: ['.workflow/verifications/shell'],
    supportsMonorepo: true,
    supportsFrontend: true,
    supportsReview: true,
    codexModes: ['implement', 'review'],
  },
  {
    id: 'verify.browser',
    aliases: ['verify browser', 'preview', 'smoke', 'screenshot'],
    keywords: ['browser', 'preview', 'smoke', 'visual', 'screenshot', 'localhost', 'vercel.app'],
    domain: 'verify',
    risk: 'low',
    sideEffects: ['browser', 'write_fs'],
    repoSignals: ['frontend_active', 'browser_needed'],
    preconditions: ['url_or_preview_available'],
    postconditions: ['browser_evidence_written'],
    evidenceOutputs: ['.workflow/verifications/browser'],
    supportsMonorepo: true,
    supportsFrontend: true,
    supportsReview: true,
    codexModes: ['frontend'],
  },
  {
    id: 'team.parallel',
    aliases: ['team', 'parallel', 'subagent', 'delegate'],
    keywords: ['parallel', 'delegate', 'subagent', 'team', 'sweep', 'across many files'],
    domain: 'ops',
    risk: 'high',
    sideEffects: ['write_fs', 'run_shell', 'git_mutation'],
    repoSignals: ['large_scope'],
    preconditions: ['disjoint_write_scope'],
    postconditions: ['orchestration_plan_written'],
    evidenceOutputs: ['.workflow/orchestration/PLAN.md', '.workflow/orchestration/STATUS.md'],
    supportsMonorepo: true,
    supportsFrontend: true,
    supportsReview: true,
    codexModes: ['implement', 'review'],
  },
  {
    id: 'ship.release',
    aliases: ['ship', 'release', 'closeout'],
    keywords: ['ship', 'release', 'closeout', 'handoff'],
    domain: 'ship',
    risk: 'high',
    sideEffects: ['write_fs', 'run_shell', 'git_mutation'],
    repoSignals: ['workflow_active'],
    preconditions: ['review_ready'],
    postconditions: ['ship_package_written'],
    evidenceOutputs: ['.workflow/reports/ship.md', '.workflow/reports/release-notes.md'],
    supportsMonorepo: true,
    supportsFrontend: true,
    supportsReview: true,
    codexModes: ['implement', 'review'],
  },
  {
    id: 'incident.triage',
    aliases: ['incident', 'regression', 'outage', 'hotfix'],
    keywords: ['incident', 'regression', 'outage', 'urgent', 'hotfix'],
    domain: 'incident',
    risk: 'high',
    sideEffects: ['run_shell', 'write_fs'],
    repoSignals: ['workflow_active'],
    preconditions: ['goal_present'],
    postconditions: ['incident_memory_written'],
    evidenceOutputs: ['.workflow/incidents', '.workflow/reports/session-report.md'],
    supportsMonorepo: true,
    supportsFrontend: true,
    supportsReview: true,
    codexModes: ['incident'],
  },
]);

function listCapabilities() {
  return CAPABILITIES.map((capability) => ({ ...capability }));
}

function capabilityById(id) {
  return CAPABILITIES.find((capability) => capability.id === id) || null;
}

function capabilityAliases(capability) {
  return [...(capability.aliases || []), ...(capability.keywords || [])].map((entry) => String(entry).toLowerCase());
}

module.exports = {
  CAPABILITIES,
  capabilityAliases,
  capabilityById,
  listCapabilities,
};
