const CAPABILITIES = Object.freeze([
  {
    id: 'research.discuss',
    aliases: ['research', 'investigate', 'analyse', 'analyze', 'audit', 'look into', 'figure out', 'incele', 'arastir', 'analiz', 'goz at', 'bir bak'],
    keywords: ['why', 'compare', 'audit', 'review', 'investigate', 'analyse', 'analyze', 'look into', 'figure out', 'help me understand', 'incele', 'arastir', 'analiz', 'goz at', 'bir bak', 'nedenini bul'],
    domain: 'research',
    risk: 'low',
    sideEffects: ['run_shell'],
    repoSignals: ['workflow_active'],
    preconditions: ['workflow_docs_ready'],
    postconditions: ['question_log_updated'],
    evidenceOutputs: ['docs/workflow/QUESTIONS.md', '.workflow/runtime/do-latest.json'],
    supportsMonorepo: true,
    supportsFrontend: true,
    supportsReview: true,
    codexModes: ['research', 'implement'],
  },
  {
    id: 'plan.execution_packet',
    aliases: ['plan', 'packet', 'roadmap', 'approach', 'put together', 'map out', 'hazirla', 'yol haritasi cikar'],
    keywords: ['plan', 'packet', 'roadmap', 'approach', 'next step', 'milestone', 'execution packet', 'milestone packet', 'put together', 'map out', 'lay out', 'hazirla', 'paketi hazirla', 'yol haritasi cikar', 'planini cikar'],
    domain: 'plan',
    risk: 'low',
    sideEffects: ['write_fs'],
    repoSignals: ['workflow_active'],
    preconditions: ['workflow_docs_ready'],
    postconditions: ['packet_compiled'],
    evidenceOutputs: ['.workflow/packets', 'docs/workflow/EXECPLAN.md'],
    supportsMonorepo: true,
    supportsFrontend: true,
    supportsReview: true,
    codexModes: ['research', 'implement'],
  },
  {
    id: 'execute.quick_patch',
    aliases: ['implement', 'fix', 'patch', 'build', 'tamamla', 'wire up', 'clean up', 'duzeltmeyi uygula'],
    keywords: ['fix', 'implement', 'patch', 'build', 'land', 'complete', 'wire up', 'clean up', 'tighten', 'make the change', 'tamamla', 'duzelt', 'duzeltmeyi uygula', 'toparla', 'iyilestir'],
    domain: 'execute',
    risk: 'medium',
    sideEffects: ['write_fs', 'run_shell'],
    repoSignals: ['workflow_active'],
    preconditions: ['goal_present'],
    postconditions: ['verification_requested'],
    evidenceOutputs: ['.workflow/verifications/shell', '.workflow/reports/review.md'],
    supportsMonorepo: true,
    supportsFrontend: true,
    supportsReview: true,
    codexModes: ['implement', 'refactor'],
  },
  {
    id: 'review.deep_review',
    aliases: ['review', 'audit', 'code review', 'pr review', 'go over', 'look over', 'inceleme', 'degerlendirme', 'urun degerlendirmesi', 'elden gecir', 'gozden gecir'],
    keywords: ['review', 'audit', 'regression', 'bug', 'risk', 'pr', 'diff', 'go over', 'look over', 'write down the risks', 'call out blockers', 'inceleme', 'degerlendirme', 'degerlendirmesi', 'elden gecir', 'gozden gecir', 'riskleri yaz', 'bulgulari yaz'],
    domain: 'review',
    risk: 'medium',
    sideEffects: ['run_shell', 'write_fs'],
    repoSignals: ['git_repo'],
    preconditions: ['git_or_patch_available'],
    postconditions: ['review_packet_written'],
    evidenceOutputs: ['.workflow/reports/review.md', '.workflow/reports/review-findings.json'],
    supportsMonorepo: true,
    supportsFrontend: true,
    supportsReview: true,
    codexModes: ['review'],
  },
  {
    id: 'review.re_review',
    aliases: ['re-review', 'rerun review', 'follow-up review'],
    keywords: ['re-review', 'rerun review', 'follow-up review', 'resolved issues'],
    domain: 'review',
    risk: 'medium',
    sideEffects: ['run_shell', 'write_fs'],
    repoSignals: ['git_repo'],
    preconditions: ['prior_review_exists'],
    postconditions: ['review_replay_written'],
    evidenceOutputs: ['.workflow/reports/review-replay.json', '.workflow/reports/review.md'],
    supportsMonorepo: true,
    supportsFrontend: true,
    supportsReview: true,
    codexModes: ['review'],
  },
  {
    id: 'frontend.ui_spec',
    aliases: ['ui spec', 'design contract', 'ui plan'],
    keywords: ['ui', 'frontend', 'screen', 'design', 'responsive', 'component', 'ux', 'make it responsive', 'polish the ui', 'responsive yap', 'tasarimi iyilestir', 'arayuz'],
    domain: 'frontend',
    risk: 'medium',
    sideEffects: ['write_fs'],
    repoSignals: ['frontend_active'],
    preconditions: ['frontend_surface_present'],
    postconditions: ['ui_spec_written'],
    evidenceOutputs: ['docs/workflow/UI-SPEC.md', 'docs/workflow/UI-PLAN.md', 'docs/workflow/DESIGN-DNA.md', 'docs/workflow/STATE-ATLAS.md', 'docs/workflow/PAGE-BLUEPRINT.md', 'docs/workflow/DESIGN.md', 'docs/workflow/COMPONENT-STRATEGY.md', 'docs/workflow/DESIGN-BENCHMARK.md'],
    supportsMonorepo: true,
    supportsFrontend: true,
    supportsReview: false,
    codexModes: ['frontend'],
  },
  {
    id: 'frontend.ui_review',
    aliases: ['ui review', 'visual audit', 'responsive audit', 'a11y audit'],
    keywords: ['ui review', 'visual', 'responsive', 'a11y', 'accessibility', 'screenshot', 'preview'],
    domain: 'frontend',
    risk: 'medium',
    sideEffects: ['run_shell', 'browser', 'write_fs'],
    repoSignals: ['frontend_active', 'browser_needed'],
    preconditions: ['frontend_surface_present'],
    postconditions: ['ui_review_written'],
    evidenceOutputs: ['docs/workflow/UI-REVIEW.md', '.workflow/verifications/browser'],
    supportsMonorepo: true,
    supportsFrontend: true,
    supportsReview: true,
    codexModes: ['frontend', 'review'],
  },
  {
    id: 'verify.shell',
    aliases: ['verify shell', 'test', 'check', 'double-check', 'run tests', 'kontrol et'],
    keywords: ['test', 'verify', 'check', 'lint', 'typecheck', 'double-check', 'run tests', 'make sure', 'kontrol et', 'test et', 'emin ol'],
    domain: 'verify',
    risk: 'low',
    sideEffects: ['run_shell'],
    repoSignals: ['workflow_active'],
    preconditions: ['command_available'],
    postconditions: ['shell_evidence_written'],
    evidenceOutputs: ['.workflow/verifications/shell'],
    supportsMonorepo: true,
    supportsFrontend: true,
    supportsReview: true,
    codexModes: ['implement', 'review'],
  },
  {
    id: 'verify.browser',
    aliases: ['verify browser', 'preview', 'smoke', 'screenshot', 'smoke test', 'previewu smoke et'],
    keywords: ['browser', 'preview', 'smoke', 'visual', 'screenshot', 'smoke test', 'capture screenshots', 'localhost', 'vercel.app', 'previewu smoke et', 'ekran goruntusu al'],
    domain: 'verify',
    risk: 'low',
    sideEffects: ['browser', 'write_fs'],
    repoSignals: ['frontend_active', 'browser_needed'],
    preconditions: ['url_or_preview_available'],
    postconditions: ['browser_evidence_written'],
    evidenceOutputs: ['.workflow/verifications/browser'],
    supportsMonorepo: true,
    supportsFrontend: true,
    supportsReview: true,
    codexModes: ['frontend'],
  },
  {
    id: 'team.parallel',
    aliases: ['team', 'parallel', 'subagent', 'delegate', 'split this up', 'parcalara bol'],
    keywords: ['parallel', 'delegate', 'subagent', 'team', 'sweep', 'across many files', 'split this up', 'fan out', 'divide the work', 'parcalara bol', 'paketlere dagit', 'ayni anda yurut'],
    domain: 'ops',
    risk: 'high',
    sideEffects: ['write_fs', 'run_shell', 'git_mutation'],
    repoSignals: ['large_scope'],
    preconditions: ['disjoint_write_scope'],
    postconditions: ['orchestration_plan_written'],
    evidenceOutputs: ['.workflow/orchestration/PLAN.md', '.workflow/orchestration/STATUS.md'],
    supportsMonorepo: true,
    supportsFrontend: true,
    supportsReview: true,
    codexModes: ['implement', 'review'],
  },
  {
    id: 'ship.release',
    aliases: ['ship', 'release', 'closeout', 'get this out', 'yayina al'],
    keywords: ['ship', 'release', 'closeout', 'handoff', 'get this out', 'send it', 'wrap it up', 'yayina al', 'teslim et'],
    domain: 'ship',
    risk: 'high',
    sideEffects: ['write_fs', 'run_shell', 'git_mutation'],
    repoSignals: ['workflow_active'],
    preconditions: ['review_ready'],
    postconditions: ['ship_package_written'],
    evidenceOutputs: ['.workflow/reports/ship.md', '.workflow/reports/release-notes.md'],
    supportsMonorepo: true,
    supportsFrontend: true,
    supportsReview: true,
    codexModes: ['implement', 'review'],
  },
  {
    id: 'incident.triage',
    aliases: ['incident', 'regression', 'outage', 'hotfix'],
    keywords: ['incident', 'regression', 'outage', 'urgent', 'hotfix'],
    domain: 'incident',
    risk: 'high',
    sideEffects: ['run_shell', 'write_fs'],
    repoSignals: ['workflow_active'],
    preconditions: ['goal_present'],
    postconditions: ['incident_memory_written'],
    evidenceOutputs: ['.workflow/incidents', '.workflow/reports/session-report.md'],
    supportsMonorepo: true,
    supportsFrontend: true,
    supportsReview: true,
    codexModes: ['incident'],
  },
]);

function listCapabilities() {
  return CAPABILITIES.map((capability) => ({ ...capability }));
}

function capabilityById(id) {
  return CAPABILITIES.find((capability) => capability.id === id) || null;
}

function capabilityAliases(capability) {
  return [...(capability.aliases || []), ...(capability.keywords || [])].map((entry) => String(entry).toLowerCase());
}

module.exports = {
  CAPABILITIES,
  capabilityAliases,
  capabilityById,
  listCapabilities,
};
