const RUNTIME_SCRIPT_CATALOG = Object.freeze({
  "raiola:audit": "node scripts/workflow/audit.js",
  "raiola:audit-repo": "node scripts/workflow/audit_repo.js",
  "raiola:repo-proof": "node scripts/workflow/repo_proof.js",
  "raiola:api-surface": "node scripts/workflow/api_surface.js",
  "raiola:fix": "node scripts/workflow/fix.js",
  "raiola:on": "node scripts/workflow/onboarding.js",
  "raiola:approval": "node scripts/workflow/approvals.js",
  "raiola:approvals": "node scripts/workflow/approvals.js",
  "raiola:assumptions": "node scripts/workflow/assumptions.js",
  "raiola:automation": "node scripts/workflow/automation.js",
  "raiola:backlog": "node scripts/workflow/backlog.js",
  "raiola:benchmark": "node scripts/workflow/benchmark.js",
  "raiola:checkpoint": "node scripts/workflow/checkpoint.js",
  "raiola:claims": "node scripts/workflow/claims.js",
  "raiola:codex": "node scripts/workflow/codex_control.js",
  "raiola:compare-golden": "node scripts/compare_golden_snapshots.ts",
  "raiola:complete-milestone": "node scripts/workflow/complete_milestone.js",
  "raiola:component-map": "node scripts/workflow/component_map.js",
  "raiola:component-strategy": "node scripts/workflow/component_strategy.js",
  "raiola:contextpack": "node scripts/workflow/context_pack.js",
  "raiola:control": "node scripts/workflow/control.js",
  "raiola:daemon": "node scripts/workflow/daemon.js",
  "raiola:dashboard": "node scripts/workflow/dashboard.js",
  "raiola:delegation-plan": "node scripts/workflow/delegation_plan.js",
  "raiola:design-debt": "node scripts/workflow/design_debt.js",
  "raiola:design-benchmark": "node scripts/workflow/design_benchmark.js",
  "raiola:design-dna": "node scripts/workflow/design_dna.js",
  "raiola:design-md": "node scripts/workflow/design_md.js",
  "raiola:discuss": "node scripts/workflow/discuss.js",
  "raiola:do": "node scripts/workflow/do.js",
  "raiola:start": "node scripts/workflow/start.js",
  "raiola:doctor": "node scripts/workflow/doctor.js",
  "raiola:ensure-isolation": "node scripts/workflow/ensure_isolation.js",
  "raiola:evidence": "node scripts/workflow/evidence.js",
  "raiola:evidence-check": "node scripts/workflow/evidence_check.js",
  "raiola:explore": "node scripts/workflow/explore.js",
  "raiola:fleet": "node scripts/workflow/fleet.js",
  "raiola:frontend-brief": "node scripts/workflow/frontend_brief.js",
  "raiola:forensics": "node scripts/workflow/forensics.js",
  "raiola:gc": "node scripts/workflow/gc.js",
  "raiola:health": "node scripts/workflow/health.js",
  "raiola:hooks": "node scripts/workflow/hooks.js",
  "raiola:hud": "node scripts/workflow/hud.js",
  "raiola:incident": "node scripts/workflow/incident.js",
  "raiola:init": "node scripts/workflow/init.js",
  "raiola:launch": "node scripts/workflow/launch.js",
  "raiola:manager": "node scripts/workflow/manager.js",
  "raiola:map-codebase": "node scripts/workflow/map_codebase.js",
  "raiola:map-frontend": "node scripts/workflow/map_frontend.js",
  "raiola:mcp": "node scripts/workflow/mcp.js",
  "raiola:migrate": "node scripts/workflow/migrate.js",
  "raiola:monorepo": "node scripts/workflow/monorepo.js",
  "raiola:monorepo-mode": "node scripts/workflow/monorepo_mode.js",
  "raiola:milestone": "node scripts/workflow/new_milestone.js",
  "raiola:milestone-edit": "node scripts/workflow/milestone_edit.js",
  "raiola:next": "node scripts/workflow/next_step.js",
  "raiola:next-prompt": "node scripts/workflow/next_prompt.js",
  "raiola:note": "node scripts/workflow/note.js",
  "raiola:notify": "node scripts/workflow/notify.js",
  "raiola:packet": "node scripts/workflow/build_packet.js",
  "raiola:packet-os": "node scripts/workflow/packet.js",
  "raiola:page-blueprint": "node scripts/workflow/page_blueprint.js",
  "raiola:patch-apply": "node scripts/workflow/patch_apply.js",
  "raiola:patch-review": "node scripts/workflow/patch_review.js",
  "raiola:patch-rollback": "node scripts/workflow/patch_rollback.js",
  "raiola:pause-work": "node scripts/workflow/pause_work.js",
  "raiola:plan-check": "node scripts/workflow/plan_check.js",
  "raiola:plant-seed": "node scripts/workflow/plant_seed.js",
  "raiola:policy": "node scripts/workflow/policy.js",
  "raiola:pr-brief": "node scripts/workflow/pr_brief.js",
  "raiola:pr-review": "node scripts/workflow/pr_review.js",
  "raiola:preview": "node scripts/workflow/preview.js",
  "raiola:profile": "node scripts/workflow/profile.js",
  "raiola:questions": "node scripts/workflow/questions.js",
  "raiola:quick": "node scripts/workflow/quick.js",
  "raiola:re-review": "node scripts/workflow/re_review.js",
  "raiola:release-notes": "node scripts/workflow/release_notes.js",
  "raiola:repair": "node scripts/workflow/repair.js",
  "raiola:responsive-matrix": "node scripts/workflow/responsive_matrix.js",
  "raiola:resume-work": "node scripts/workflow/resume_work.js",
  "raiola:review": "node scripts/workflow/review.js",
  "raiola:review-mode": "node scripts/workflow/review_mode.js",
  "raiola:review-orchestrate": "node scripts/workflow/review_orchestrate.js",
  "raiola:review-tasks": "node scripts/workflow/review_task_graph.js",
  "raiola:roadmap-audit": "node scripts/workflow/roadmap_audit.js --assert",
  "raiola:route": "node scripts/workflow/model_route.js",
  "raiola:save-memory": "node scripts/workflow/save_memory.js",
  "raiola:secure": "node scripts/workflow/secure_phase.js",
  "raiola:session-report": "node scripts/workflow/session_report.js",
  "raiola:sessions": "node scripts/workflow/sessions.js",
  "raiola:setup": "node scripts/workflow/setup.js",
  "raiola:spec": "node scripts/workflow/spec.js",
  "raiola:plan": "node scripts/workflow/plan.js",
  "raiola:build": "node scripts/workflow/build.js",
  "raiola:test": "node scripts/workflow/test.js",
  "raiola:simplify": "node scripts/workflow/simplify.js",
  "raiola:ship": "node scripts/workflow/ship.js",
  "raiola:ship-readiness": "node scripts/workflow/ship_readiness.js",
  "raiola:stats": "node scripts/workflow/stats.js",
  "raiola:state-atlas": "node scripts/workflow/state_atlas.js",
  "raiola:step-fulfillment": "node scripts/workflow/step_fulfillment.js",
  "raiola:subagents": "node scripts/workflow/subagents.js",
  "raiola:switch-workstream": "node scripts/workflow/switch_workstream.js",
  "raiola:team": "node scripts/workflow/team.js",
  "raiola:team-resume": "node scripts/workflow/team.js resume",
  "raiola:team-runtime": "node scripts/workflow/team_runtime.js",
  "raiola:team-status": "node scripts/workflow/team.js status",
  "raiola:team-stop": "node scripts/workflow/team.js stop",
  "raiola:tempo": "node scripts/workflow/tempo.js",
  "raiola:thread": "node scripts/workflow/thread.js",
  "raiola:ui-direction": "node scripts/workflow/ui_direction.js",
  "raiola:ui-recipe": "node scripts/workflow/ui_recipe.js",
  "raiola:ui-plan": "node scripts/workflow/ui_plan.js",
  "raiola:ui-review": "node scripts/workflow/ui_review.js",
  "raiola:ui-spec": "node scripts/workflow/ui_spec.js",
  "raiola:uninstall": "node scripts/workflow/uninstall.js",
  "raiola:update": "node scripts/workflow/update.js",
  "raiola:validate-contract": "node scripts/workflow/validate_contract.js",
  "raiola:validation-map": "node scripts/workflow/validation_map.js",
  "raiola:verify-browser": "node scripts/workflow/verify_browser.js",
  "raiola:verify-shell": "node scripts/workflow/verify_shell.js",
  "raiola:verify": "node scripts/workflow/verify.js",
  "raiola:verify-work": "node scripts/workflow/verify_work.js",
  "raiola:window": "node scripts/workflow/window_monitor.js",
  "raiola:workspaces": "node scripts/workflow/workspaces_center.js",
  "raiola:workstreams": "node scripts/workflow/workstreams.js",
  "raiola:repo-config": "node scripts/workflow/repo_config.js",
  "raiola:trust": "node scripts/workflow/trust_center.js",
  "raiola:release-control": "node scripts/workflow/release_control.js",
  "raiola:control-plane-publish": "node scripts/workflow/control_plane_publish.js",
  "raiola:autopilot": "node scripts/workflow/autopilot.js",
  "raiola:handoff": "node scripts/workflow/handoff.js",
  "raiola:team-control": "node scripts/workflow/team_control_room.js",
  "raiola:measure": "node scripts/workflow/measure.js",
  "raiola:explain": "node scripts/workflow/explain.js",
  "raiola:lifecycle": "node scripts/workflow/lifecycle_center.js",
  "raiola:operate": "node scripts/workflow/operate.js",
  "raiola:repo-control": "node scripts/workflow/repo_control.js",
  "raiola:workspace-impact": "node scripts/workflow/workspace_impact.js",
  "raiola:monorepo-control": "node scripts/workflow/monorepo_control.js",
  "raiola:frontend-control": "node scripts/workflow/frontend_control.js",
  "raiola:safety-control": "node scripts/workflow/safety_control.js",
  "raiola:codex-mission": "node scripts/workflow/codex_control.js mission",
  "raiola:supervisor": "node scripts/workflow/runtime_supervisor.js",
  "raiola:telemetry": "node scripts/workflow/telemetry.js",
  "raiola:mcp-stdio": "node bin/raiola-mcp.js --server workflow-state --repo .",
});

function listRuntimeScriptNames() {
  return Object.keys(RUNTIME_SCRIPT_CATALOG);
}

function readRuntimeScriptCatalog() {
  return { ...RUNTIME_SCRIPT_CATALOG };
}

module.exports = {
  RUNTIME_SCRIPT_CATALOG,
  listRuntimeScriptNames,
  readRuntimeScriptCatalog,
};
